version: '1'

services:
  frontend:
    image: djawad02/frontend-microservice:b9b25e294d4a042ff58d76771646ebbd07f8253a
    ports:
      - "3000:3000"
    networks:
      - proj-network

  appointments:
    image: djawad02/appointment-microservice:4217488fc22b7de0443eeedca878b85c529a951a
    networks:
      - proj-network
    ports:
      - "7070:7070"
    depends_on:
      - database

  doctors:
    image: djawad02/doctor-microservice:13318b5e842b324b75240e50ce02e320ee02663c
    networks:
      - proj-network
    ports:
      - "9090:9090"
    depends_on:
      - database

  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: appointmentsdb
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    ports:
      - "3306:3306"
    networks:
      - proj-network

networks:
  proj-network:
    driver: bridge
