version: '1'

services:
  frontend:
    image: djawad02/frontend-microservice:808469f6083e308a372bee3249f0ee8dadd2f369
    ports:
      - "3000:3000"
    networks:
      - proj-network

  appointments:
    image: djawad02/appointment-microservice:5964bbb63eadb74ddf0d61ff3e2f80a860144789
    networks:
      - proj-network
    ports:
      - "7070:7070"
    depends_on:
      - database

  doctors:
    image: djawad02/doctor-microservice:444b33d22392a9d3475e0277063f0f88ef2b4c0f
    networks:
      - proj-network
    ports:
      - "9090:9090"
    depends_on:
      - database

  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: appointmentsdb
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    ports:
      - "3306:3306"
    networks:
      - proj-network

networks:
  proj-network:
    driver: bridge
