version: '1'

services:
  frontend:
    image: djawad02/frontend-microservice:808469f6083e308a372bee3249f0ee8dadd2f369
    ports:
      - "3000:3000"
    networks:
      - proj-network

  appointments:
    image: djawad02/appointment-microservice:8ae34040c1f2d3a4691d477226768336b47041eb
    networks:
      - proj-network
    ports:
      - "7070:7070"
    depends_on:
      - database

  doctors:
    image: djawad02/doctor-microservice:050d71a981c5f04ebee2a3795ae5547d49ba2ef6
    networks:
      - proj-network
    ports:
      - "9090:9090"
    depends_on:
      - database

  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: appointmentsdb
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    ports:
      - "3306:3306"
    networks:
      - proj-network

networks:
  proj-network:
    driver: bridge
