apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctors-microservice
spec:
  replicas: 3
  selector:
    matchLabels:
      app: doctors
  template:
    metadata:
      labels:
        app: doctors
    spec:
      containers:
      - name: doctors-container
        image: djawad02/doctor-microservice:latest
        env:
        - name: DATABASE_HOST
          value: doctors-db-service
        - name: DATABASE_PORT
          value: "3306"
        ports:
        - containerPort: 9090
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
          requests:
            memory: "64Mi"
            cpu: "50m"
        readinessProbe:
          httpGet:
            path: /healthz
            port: 7070
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /healthz
            port: 7070
          initialDelaySeconds: 15
          periodSeconds: 20
        
---

apiVersion: v1
kind: Service
metadata:
  name: doctors-microservice
spec:
  selector:
    app: doctors
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9090
