apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctors-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctors
  template:
    metadata:
      labels:
        app: doctors
    spec:
      containers:
      - name: doctors-container
        image: djawad02/doctor-microservice:latest
        env:
        - name: DATABASE_HOST
          value: doctors-db-service
        - name: DATABASE_PORT
          value: "3306"
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: user-details
          mountPath: /user
          readOnly: true

      volumes:
      - name: user-details
        configMap:
          name: doctors
        
---

apiVersion: v1
kind: Service
metadata:
  name: doctors-microservice
spec:
  selector:
    app: doctors
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9090
